version: '3.7'

services:
  seed_node-ts-docker:
    build:
      target: production
    command: node build/index.js

#  override for production environment
#  docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d